# Generated by Django 3.2.11 on 2022-01-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('guardians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianstudent',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
    ]
