# Generated by Django 3.2.3 on 2021-06-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('students', '0002_auto_20210617_2313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAchivement',
            new_name='StudentAchievement',
        ),
    ]
