# Generated by Django 3.2.11 on 2022-01-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_auto_20220105_1403'),
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgrade',
            old_name='is_finish',
            new_name='is_finished',
        ),
        migrations.RemoveField(
            model_name='studenttopicmastery',
            name='date_mastery',
        ),
        migrations.RemoveField(
            model_name='studenttopicmastery',
            name='is_block',
        ),
        migrations.RemoveField(
            model_name='studenttopicmastery',
            name='is_mastery',
        ),
        migrations.RemoveField(
            model_name='studenttopicmastery',
            name='topic',
        ),
        migrations.AddField(
            model_name='studenttopicmastery',
            name='mastery_level',
            field=models.CharField(choices=[(0, 'Not practiced'), (1, 'Novice'), (2, 'Competent'), (3, 'Master')], default=0, max_length=32),
        ),
        migrations.AddField(
            model_name='studenttopicmastery',
            name='topic_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kb.topicgrade'),
        ),
    ]
