# Generated by Django 3.2.12 on 2022-03-04 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_alter_prerequisite_prerequisites'),
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttopicgradestatus',
            name='topic_grade',
        ),
        migrations.AddField(
            model_name='studenttopicgradestatus',
            name='topic',
            field=models.ForeignKey(default=98, on_delete=django.db.models.deletion.CASCADE, to='kb.topic'),
            preserve_default=False,
        ),
    ]
