# Generated by Django 3.2.11 on 2022-01-19 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20220106_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='student',
            name='avatar_favorites',
        ),
        migrations.AddField(
            model_name='student',
            name='avatar_accessories',
            field=models.ForeignKey(limit_choices_to={'type_of': 'ACCESSORIES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.avatar'),
        ),
        migrations.AddField(
            model_name='student',
            name='avatar_clothes',
            field=models.ForeignKey(limit_choices_to={'type_of': 'CLOTHES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.avatar'),
        ),
        migrations.AddField(
            model_name='student',
            name='avatar_head',
            field=models.ForeignKey(limit_choices_to={'type_of': 'HEAD/HAIR'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.avatar'),
        ),
        migrations.AddField(
            model_name='student',
            name='avatar_pants',
            field=models.ForeignKey(limit_choices_to={'type_of': 'PANTS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.avatar'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='type_of',
            field=models.CharField(choices=[(1, 'Accessories'), (2, 'Head/Hair'), (3, 'Clothes'), (4, 'Pants')], max_length=25, null=True),
        ),
    ]
