# Generated by Django 3.2.4 on 2021-07-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar_favorites',
            field=models.ManyToManyField(blank=True, related_name='Favoritos', to='students.Avatar'),
        ),
    ]
