# Generated by Django 3.2.12 on 2022-03-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_alter_prerequisite_prerequisites'),
        ('students', '0004_rename_studenttopicgradestatus_studenttopicstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenttopicmastery',
            name='topic_grade',
        ),
        migrations.AddField(
            model_name='studenttopicmastery',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kb.topic'),
        ),
    ]
