# Generated by Django 3.2.11 on 2022-01-20 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20220119_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar_accessories',
            field=models.ForeignKey(limit_choices_to={'type_of': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.avatar'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar_clothes',
            field=models.ForeignKey(limit_choices_to={'type_of': 3}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.avatar'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar_head',
            field=models.ForeignKey(limit_choices_to={'type_of': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.avatar'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar_pants',
            field=models.ForeignKey(limit_choices_to={'type_of': 4}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='students.avatar'),
        ),
    ]
