# Generated by Django 3.2.12 on 2022-03-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_alter_prerequisite_prerequisites'),
        ('students', '0005_auto_20220304_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttopicmastery',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topic_mastery', to='kb.topic'),
        ),
    ]
