# Generated by Django 3.2.11 on 2022-01-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_avatar_type_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='type_of',
            field=models.CharField(choices=[('ACCESSORIES', 'Accessories'), ('HEAD', 'Head/Hair'), ('CLOTHES', 'Clothes'), ('PANTS', 'Pants')], max_length=25, null=True),
        ),
    ]
