# Generated by Django 3.2.12 on 2022-04-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20220425_1842'),
        ('students', '0008_student_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.classroom'),
            preserve_default=False,
        ),
    ]
