# Generated by Django 3.2.12 on 2022-03-07 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_alter_prerequisite_prerequisites'),
        ('students', '0009_alter_studenttopicmastery_mastery_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttopicmastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
        migrations.AlterField(
            model_name='studenttopicmastery',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mastery', to='kb.topic'),
        ),
        migrations.AlterField(
            model_name='studenttopicstatus',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='kb.topic'),
        ),
    ]
