# Generated by Django 3.2.11 on 2022-02-07 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0001_initial'),
        ('students', '0010_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avatar_accessories',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_of': 'ACCESSORIES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar_clothes',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_of': 'CLOTHES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar_head',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_of': 'HEAD'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar'),
        ),
        migrations.AlterField(
            model_name='student',
            name='avatar_pants',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_of': 'PANTS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar'),
        ),
    ]
