# Generated by Django 3.2.13 on 2022-07-11 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20220711_2159'),
        ('kb', '0016_auto_20220525_0236'),
        ('students', '0011_auto_20220525_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.UUIDField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('number_of_questions', models.IntegerField(default=10)),
                ('start_at', models.DateField(blank=True, null=True)),
                ('end_at', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Expired', 'Expired')], default='Pending', max_length=16)),
                ('assigned_administrative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.administrativepersonnel')),
                ('assigned_subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.subscriber')),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
