# Generated by Django 3.2.11 on 2022-02-07 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20220207_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
