# Generated by Django 3.2.13 on 2022-07-09 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20220709_0207'),
        ('kb', '0016_auto_20220525_0236'),
        ('students', '0012_studenthomework'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthomework',
            name='assigned_administrative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.administrativepersonnel'),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='assigned_subscriber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.subscriber'),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.teacher'),
        ),
        migrations.AddField(
            model_name='studenthomework',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending'), ('Expired', 'Expired')], default='Pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kb.topic'),
        ),
    ]
