# Generated by Django 3.2.13 on 2022-07-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studenthomework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
