# Generated by Django 3.2.11 on 2022-02-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_delete_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='avatar_accessories',
        ),
        migrations.RemoveField(
            model_name='student',
            name='avatar_clothes',
        ),
        migrations.RemoveField(
            model_name='student',
            name='avatar_head',
        ),
        migrations.RemoveField(
            model_name='student',
            name='avatar_pants',
        ),
    ]
