# Generated by Django 3.2.13 on 2022-07-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20220709_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='start_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
