# Generated by Django 3.2.13 on 2022-07-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20220709_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthomework',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
