# Generated by Django 3.2.12 on 2022-02-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20220214_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
