# Generated by Django 3.2.11 on 2022-02-19 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='int_period_start_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
