# Generated by Django 3.1.7 on 2021-04-02 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('random_slug', models.UUIDField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp de creación')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp de modificación')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kb.grade')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
