# Generated by Django 3.2.13 on 2022-07-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField(null=True)),
                ('sentAt', models.DateTimeField(auto_now_add=True, verbose_name='Sent at')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
