# Generated by Django 3.2.13 on 2022-07-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20220709_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
