# Generated by Django 3.2.11 on 2022-02-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20220214_1309'),
        ('avatars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteAvatarCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('skin_tone', models.CharField(blank=True, max_length=7, null=True)),
                ('avatar_accessorie', models.ForeignKey(blank=True, limit_choices_to={'type_of': 'ACCESSORIES'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar')),
                ('avatar_clothes', models.ForeignKey(limit_choices_to={'type_of': 'CLOTHES'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar')),
                ('avatar_head', models.ForeignKey(limit_choices_to={'type_of': 'HEAD'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar')),
                ('avatar_pants', models.ForeignKey(limit_choices_to={'type_of': 'PANTS'}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='avatars.avatar')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
