# Generated by Django 3.2.11 on 2022-02-16 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('guardians', '0004_alter_guardian_user'),
        ('plans', '0002_guardianstudentplan_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='guardian_student_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.guardianstudentplan'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.order'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
        migrations.AddField(
            model_name='order',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guardians.guardian'),
        ),
        migrations.AddField(
            model_name='cardtransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.order'),
        ),
    ]
