# Generated by Django 3.2.13 on 2022-07-11 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20220711_2159'),
        ('guardians', '0006_auto_20220525_0236'),
        ('payments', '0009_auto_20220526_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
        migrations.AddField(
            model_name='order',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.teacher'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.teacher'),
        ),
        migrations.AlterField(
            model_name='order',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardians.guardian'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guardians.guardian'),
        ),
    ]
