# Generated by Django 3.2.13 on 2022-07-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20220709_1823'),
        ('payments', '0010_auto_20220709_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='order',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
    ]
