# Generated by Django 3.2.13 on 2022-08-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_discountcode_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='forWho',
            field=models.CharField(choices=[('FOR_GUARDIAN', 'FOR_GUARDIAN'), ('FOR_TEACHER', 'FOR_TEACHER'), ('FOR_SUBSCRIBER', 'FOR_SUBSCRIBER'), ('FOR_ALL', 'FOR_ALL')], default='FOR_ALL', max_length=255),
        ),
    ]
