# Generated by Django 3.2.13 on 2022-08-22 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_discountcode_forwho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcode',
            old_name='forWho',
            new_name='for_who',
        ),
    ]
