# Generated by Django 3.2.3 on 2021-06-04 18:57

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0002_alter_level_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achivement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('hex_color', models.CharField(blank=True, max_length=16, null=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(editable=False)),
                ('image', models.TextField(null=True)),
                ('engangement_points', models.IntegerField(null=True)),
                ('coins_earned', models.IntegerField(null=True)),
                ('level_required', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='experiences.level')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
