# Generated by Django 3.2.11 on 2022-02-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_bankmovement_banknegativemovement_bankpositivemovement'),
        ('wallets', '0003_alter_coinwallet_student'),
        ('students', '0015_student_points'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('bankpositivemovement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.bankpositivemovement')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounting.bankpositivemovement',),
        ),
        migrations.CreateModel(
            name='BankDepositTransaction',
            fields=[
                ('withdraw_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallets.withdraw')),
                ('bank_deposit', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bankAccountDeposit', to='bank.bankdeposit')),
            ],
            options={
                'abstract': False,
            },
            bases=('wallets.withdraw',),
        ),
        migrations.CreateModel(
            name='BankWallet',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.account')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bankWallet', to='students.student')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounting.account',),
        ),
        migrations.CreateModel(
            name='BankWithdraw',
            fields=[
                ('banknegativemovement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.banknegativemovement')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounting.banknegativemovement',),
        ),
        migrations.CreateModel(
            name='BankWithdrawTransaction',
            fields=[
                ('deposit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallets.deposit')),
                ('bank_withdraw', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bankAccountWithdraw', to='bank.bankwithdraw')),
            ],
            options={
                'abstract': False,
            },
            bases=('wallets.deposit',),
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
