# Generated by Django 3.2.11 on 2022-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20220218_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('name', models.CharField(max_length=64)),
                ('period', models.IntegerField(default=0)),
                ('requireCoin', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bankdeposittransaction',
            name='bank_deposit',
        ),
        migrations.RemoveField(
            model_name='bankdeposittransaction',
            name='withdraw_ptr',
        ),
        migrations.RemoveField(
            model_name='bankwithdraw',
            name='banknegativemovement_ptr',
        ),
        migrations.RemoveField(
            model_name='bankwithdrawtransaction',
            name='bank_withdraw',
        ),
        migrations.RemoveField(
            model_name='bankwithdrawtransaction',
            name='deposit_ptr',
        ),
        migrations.DeleteModel(
            name='BankDeposit',
        ),
        migrations.DeleteModel(
            name='BankDepositTransaction',
        ),
        migrations.DeleteModel(
            name='BankWithdraw',
        ),
        migrations.DeleteModel(
            name='BankWithdrawTransaction',
        ),
    ]
