# Generated by Django 3.2.4 on 2021-07-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_movement_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='positive_side',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right')], default='R', max_length=16),
        ),
    ]
