# Generated by Django 3.2.11 on 2022-02-18 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_bankmovement_banknegativemovement_bankpositivemovement'),
        ('bank', '0002_auto_20220218_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmovement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bankwallet', verbose_name='Cuenta'),
        ),
    ]
