# Generated by Django 3.2.4 on 2021-07-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_account_positive_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha Movimiento'),
        ),
    ]
