# Generated by Django 3.2.11 on 2022-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_bankmovement_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='positive_side',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('I', 'I')], default='R', max_length=16),
        ),
        migrations.AlterField(
            model_name='bankmovement',
            name='side',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('I', 'I')], max_length=1, verbose_name='Lado'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='side',
            field=models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('I', 'I')], max_length=1, verbose_name='Lado'),
        ),
    ]
