# Generated by Django 3.2.3 on 2021-06-16 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerOptionAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('order', models.PositiveIntegerField(default=10)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_content.answeroptionasset_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AddField(
            model_name='questionasset',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_content.questionasset_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='answeroption',
            name='random_slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='random_slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='questionasset',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.question'),
        ),
        migrations.CreateModel(
            name='AnswerOptionAudioAsset',
            fields=[
                ('answeroptionasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.answeroptionasset')),
                ('audio_file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.answeroptionasset',),
        ),
        migrations.CreateModel(
            name='AnswerOptionImageAsset',
            fields=[
                ('answeroptionasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.answeroptionasset')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.answeroptionasset',),
        ),
        migrations.CreateModel(
            name='AnswerOptionVideoAsset',
            fields=[
                ('answeroptionasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.answeroptionasset')),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('content.answeroptionasset',),
        ),
        migrations.AddField(
            model_name='answeroptionasset',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.answeroption'),
        ),
    ]
