# Generated by Django 3.2.4 on 2021-07-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_questionasset_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionasset',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
