# Generated by Django 3.2.3 on 2021-06-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210608_1446'),
        ('universals', '0002_auto_20210608_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='universals.universaltopic'),
        ),
        migrations.AlterField(
            model_name='questionasset',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
