# Generated by Django 3.2.3 on 2021-06-16 20:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210616_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroptionaudioasset',
            name='answeroptionasset_ptr',
        ),
        migrations.RemoveField(
            model_name='answeroptionimageasset',
            name='answeroptionasset_ptr',
        ),
        migrations.RemoveField(
            model_name='answeroptionvideoasset',
            name='answeroptionasset_ptr',
        ),
        migrations.AddField(
            model_name='answeroptiontranslation',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='answeroptiontranslation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='answeroptiontranslation',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answeroptiontranslation',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AnswerOptionAsset',
        ),
        migrations.DeleteModel(
            name='AnswerOptionAudioAsset',
        ),
        migrations.DeleteModel(
            name='AnswerOptionImageAsset',
        ),
        migrations.DeleteModel(
            name='AnswerOptionVideoAsset',
        ),
    ]
