# Generated by Django 3.1.7 on 2021-04-02 18:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp de creación')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp de modificación')),
                ('hex_color', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp de creación')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp de modificación')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('random_slug', models.UUIDField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp de creación')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp de modificación')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.grade')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp de creación')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp de modificación')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp de creación')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp de modificación')),
                ('standard_code', models.CharField(blank=True, max_length=128, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('area_of_knowledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kb.areaofknowledge')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='kb.topic')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionAudioAsset',
            fields=[
                ('questionasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.PROTECT, parent_link=True, primary_key=True, serialize=False, to='kb.questionasset')),
                ('audio_file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('kb.questionasset',),
        ),
        migrations.CreateModel(
            name='QuestionImageAsset',
            fields=[
                ('questionasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.PROTECT, parent_link=True, primary_key=True, serialize=False, to='kb.questionasset')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('kb.questionasset',),
        ),
        migrations.CreateModel(
            name='QuestionVideoAsset',
            fields=[
                ('questionasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.PROTECT, parent_link=True, primary_key=True, serialize=False, to='kb.questionasset')),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('kb.questionasset',),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.topic'),
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('random_slug', models.UUIDField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp de creación')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp de modificación')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.question')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TopicTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=128)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='kb.topic')),
            ],
            options={
                'verbose_name': 'topic Translation',
                'db_table': 'kb_topic_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('question_text', ckeditor.fields.RichTextField(blank=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='kb.question')),
            ],
            options={
                'verbose_name': 'question Translation',
                'db_table': 'kb_question_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GradeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=128, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='kb.grade')),
            ],
            options={
                'verbose_name': 'grade Translation',
                'db_table': 'kb_grade_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AreaOfKnowledgeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(editable=False)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='kb.areaofknowledge')),
            ],
            options={
                'verbose_name': 'area of knowledge Translation',
                'db_table': 'kb_areaofknowledge_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AnswerOptionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('answer_text', models.CharField(max_length=256)),
                ('explanation', ckeditor.fields.RichTextField(blank=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translations', to='kb.answeroption')),
            ],
            options={
                'verbose_name': 'answer option Translation',
                'db_table': 'kb_answeroption_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
