# Generated by Django 3.2.11 on 2022-01-05 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='topic_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Topic_grade', to='kb.topicgrade'),
        ),
        migrations.AlterField(
            model_name='topicgrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.grade'),
        ),
        migrations.AlterField(
            model_name='topicgrade',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.topic'),
        ),
    ]
