# Generated by Django 3.2.12 on 2022-03-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisite',
            name='topic_grade',
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='topic',
            field=models.ForeignKey(default=98, on_delete=django.db.models.deletion.PROTECT, related_name='Topic', to='kb.topic'),
            preserve_default=False,
        ),
    ]
