# Generated by Django 3.2.7 on 2021-12-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_alter_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofknowledge',
            name='island_image',
            field=models.ImageField(blank=True, help_text='The image of the island', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='areaofknowledge',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for practice selection', null=True, upload_to=''),
        ),
    ]
