# Generated by Django 3.2.11 on 2022-01-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_auto_20220105_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionttsasset',
            name='tts_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
