# Generated by Django 3.2.12 on 2022-03-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0002_auto_20220304_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='kb.Topic'),
        ),
    ]
