# Generated by Django 3.2.11 on 2022-01-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_auto_20211206_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTTSAsset',
            fields=[
                ('questionasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kb.questionasset')),
                ('tts_file', models.FileField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
            bases=('kb.questionasset',),
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='advance_minum',
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='advance_percentage',
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='universal_topic',
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='kb.TopicGrade'),
        ),
        migrations.RemoveField(
            model_name='prerequisite',
            name='topic_grade',
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='topic_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Topic_grade', to='kb.topicgrade'),
        ),
    ]
