# Generated by Django 3.2.9 on 2022-01-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_auto_20211206_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='video_assitor',
            field=models.URLField(blank=True, null=True),
        ),
    ]
