# Generated by Django 3.2.11 on 2022-01-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_alter_questionttsasset_tts_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofknowledgetranslation',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
