# Generated by Django 3.2.3 on 2021-06-08 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_alter_areaofknowledge_id'),
        ('universals', '0002_auto_20210608_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofknowledge',
            name='universal_area_knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='universals.universalareaofknowledge'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='prerequisite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='universal_topic',
            field=models.ManyToManyField(blank=True, to='universals.UniversalTopic'),
        ),
        migrations.AlterField(
            model_name='topicgrade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
