# Generated by Django 3.2.11 on 2022-01-14 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_alter_areaofknowledgetranslation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kb.grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='kb.topic'),
            preserve_default=False,
        ),
    ]
