# Generated by Django 3.2.11 on 2022-01-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0005_auto_20220113_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic_grade',
        ),
    ]
