# Generated by Django 3.2.3 on 2021-06-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_auto_20210616_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofknowledge',
            name='image',
            field=models.ImageField(blank=True, help_text='The image of the island', null=True, upload_to=''),
        ),
    ]
