# Generated by Django 3.2.11 on 2022-01-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0006_remove_question_topic_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topictranslation',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
