# Generated by Django 3.2.3 on 2021-06-16 18:15

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0007_alter_areaofknowledge_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='name',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='audience',
        ),
        migrations.CreateModel(
            name='GradeTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=128, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='kb.grade')),
            ],
            options={
                'verbose_name': 'grade Translation',
                'db_table': 'kb_grade_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
