# Generated by Django 3.2.11 on 2022-01-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0008_remove_topic_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='video_assitor',
            new_name='video_assistor',
        ),
    ]
