# Generated by Django 3.2.11 on 2022-01-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0009_rename_video_assitor_topic_video_assistor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimageasset',
            name='image',
            field=models.URLField(),
        ),
    ]
