# Generated by Django 3.2.11 on 2022-02-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0010_alter_questionimageasset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofknowledge',
            name='deleted_timestamp',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp'),
        ),
        migrations.AddField(
            model_name='areaofknowledge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
