# Generated by Django 3.2.11 on 2022-02-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0012_auto_20220201_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofknowledge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
