# Generated by Django 3.2.7 on 2021-10-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('block', '0001_initial'),
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockquestionpresentation',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kb.question'),
        ),
        migrations.AddField(
            model_name='blockquestion',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='block.block'),
        ),
        migrations.AddField(
            model_name='blockquestion',
            name='chosen_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kb.answeroption'),
        ),
        migrations.AddField(
            model_name='blockquestion',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kb.question'),
        ),
        migrations.AddField(
            model_name='blockpresentation',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='block.block'),
        ),
        migrations.AddField(
            model_name='blockconfiguration',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='block.block'),
        ),
        migrations.AddField(
            model_name='blockconfiguration',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='block.blockconfigurationkeyword'),
        ),
        migrations.AddField(
            model_name='block',
            name='questions',
            field=models.ManyToManyField(through='block.BlockQuestion', to='kb.Question'),
        ),
    ]
