# Generated by Django 3.2.3 on 2021-06-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('block', '0001_initial'),
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='student',
            field=models.ManyToManyField(blank=True, to='students.Student'),
        ),
        migrations.AddField(
            model_name='block',
            name='topics',
            field=models.ManyToManyField(blank=True, to='kb.Topic'),
        ),
        migrations.AddField(
            model_name='block',
            name='type_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='block.blocktype'),
        ),
        migrations.AlterUniqueTogether(
            name='blocktypetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
