# Generated by Django 3.2.5 on 2021-09-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockconfiguration',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='blocktypeconfiguration',
            name='data_type',
        ),
    ]
