# Generated by Django 3.2.3 on 2021-06-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='battery_points',
            field=models.IntegerField(null=True),
        ),
    ]
