# Generated by Django 3.2.3 on 2021-06-16 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('kb', '0001_initial'),
        ('block', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockpresentation',
            options={},
        ),
        migrations.RemoveField(
            model_name='block',
            name='battery_points',
        ),
        migrations.RemoveField(
            model_name='block',
            name='engangement_points',
        ),
        migrations.RemoveField(
            model_name='blockconfiguration',
            name='deleted_timestamp',
        ),
        migrations.RemoveField(
            model_name='blockconfiguration',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='blockconfiguration',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='blockconfiguration',
            name='random_slug',
        ),
        migrations.RemoveField(
            model_name='blockconfigurationkeyword',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='blockconfigurationkeyword',
            name='random_slug',
        ),
        migrations.RemoveField(
            model_name='blockconfigurationkeyword',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blocktype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='blocktypeconfiguration',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='blocktypeconfiguration',
            name='random_slug',
        ),
        migrations.AddField(
            model_name='block',
            name='battery_points_available',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='battery_points_earned',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='coins_available',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='engangement_points_available',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='engangement_points_earned',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='blockpresentation',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='block.block'),
        ),
        migrations.AlterField(
            model_name='block',
            name='coins_earned',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='These are the topics covered in this block', to='kb.Topic'),
        ),
        migrations.AlterField(
            model_name='blockquestion',
            name='chosen_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.answeroption'),
        ),
        migrations.AlterField(
            model_name='blockquestion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CORRECT', 'Correct'), ('INCORRECT', 'Incorrect')], default='PENDING', max_length=128),
        ),
    ]
