# Generated by Django 3.2.11 on 2022-01-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('block', '0002_initial'),
        ('kb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockpresentation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='blockconfiguration',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block.block'),
        ),
        migrations.AddField(
            model_name='blockconfiguration',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block.blockconfigurationkeyword'),
        ),
        migrations.AddField(
            model_name='block',
            name='questions',
            field=models.ManyToManyField(to='kb.Question'),
        ),
        migrations.AddField(
            model_name='block',
            name='students',
            field=models.ManyToManyField(blank=True, to='students.Student'),
        ),
        migrations.AddField(
            model_name='block',
            name='topic_grade',
            field=models.ForeignKey(help_text='This is the topic covered in this block', on_delete=django.db.models.deletion.PROTECT, to='kb.topicgrade'),
        ),
        migrations.AddField(
            model_name='block',
            name='type_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='block.blocktype'),
        ),
        migrations.AlterUniqueTogether(
            name='blocktypetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
