# Generated by Django 3.2.5 on 2021-09-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20210903_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='student',
            new_name='students',
        ),
        migrations.RemoveField(
            model_name='block',
            name='battery_points_earned',
        ),
        migrations.RemoveField(
            model_name='block',
            name='coins_earned',
        ),
        migrations.RemoveField(
            model_name='block',
            name='engangement_points_earned',
        ),
        migrations.AlterField(
            model_name='block',
            name='battery_points_available',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
    ]
