# Generated by Django 3.2.12 on 2022-03-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='coins_per_question',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
