# Generated by Django 3.2.11 on 2022-01-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_auto_20220105_1403'),
        ('students', '0003_auto_20220105_1403'),
        ('block', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='first_presentation_timestamp',
        ),
        migrations.RemoveField(
            model_name='block',
            name='last_presentation_timestamp',
        ),
        migrations.RemoveField(
            model_name='block',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='blockpresentation',
            name='deleted_timestamp',
        ),
        migrations.RemoveField(
            model_name='blockpresentation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='blockquestionpresentation',
            name='block_question',
        ),
        migrations.RemoveField(
            model_name='blockquestionpresentation',
            name='presentation_timestamp',
        ),
        migrations.RemoveField(
            model_name='blockquestionpresentation',
            name='submission_timestamp',
        ),
        migrations.AddField(
            model_name='block',
            name='block_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='block',
            name='topic_grade',
            field=models.ForeignKey(help_text='This is the topic covered in this block', null=True, on_delete=django.db.models.deletion.PROTECT, to='kb.topicgrade'),
        ),
        migrations.AddField(
            model_name='blockpresentation',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AddField(
            model_name='blockquestionpresentation',
            name='block_presentation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='block.blockpresentation'),
        ),
        migrations.AddField(
            model_name='blockquestionpresentation',
            name='chosen_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kb.answeroption'),
        ),
        migrations.AddField(
            model_name='blockquestionpresentation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CORRECT', 'Correct'), ('INCORRECT', 'Incorrect')], default='PENDING', max_length=32),
        ),
        migrations.AddField(
            model_name='blockquestionpresentation',
            name='topic_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kb.topicgrade'),
        ),
        migrations.AlterField(
            model_name='block',
            name='modality',
            field=models.CharField(choices=[('AI', 'AI'), ('PATH', 'Choose your path'), ('HOMEWORK', 'Homework')], default='AI', max_length=128),
        ),
        migrations.AlterField(
            model_name='block',
            name='questions',
            field=models.ManyToManyField(to='kb.Question'),
        ),
        migrations.AlterField(
            model_name='blockpresentation',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.block'),
        ),
        migrations.AlterField(
            model_name='blockquestionpresentation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.question'),
        ),
        migrations.DeleteModel(
            name='BlockQuestion',
        ),
    ]
