# Generated by Django 3.2.11 on 2022-01-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0001_initial'),
        ('students', '0002_student_user'),
        ('block', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='topic_grade',
            field=models.ForeignKey(help_text='This is the topic covered in this block', on_delete=django.db.models.deletion.PROTECT, to='kb.topicgrade'),
        ),
        migrations.AlterField(
            model_name='blockconfiguration',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block.block'),
        ),
        migrations.AlterField(
            model_name='blockconfiguration',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block.blockconfigurationkeyword'),
        ),
        migrations.AlterField(
            model_name='blockconfigurationkeyword',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='blockpresentation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='blockquestionpresentation',
            name='block_presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.blockpresentation'),
        ),
        migrations.AlterField(
            model_name='blockquestionpresentation',
            name='topic_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.topicgrade'),
        ),
        migrations.AlterField(
            model_name='blocktypeconfiguration',
            name='block_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block.blocktype'),
        ),
        migrations.AlterField(
            model_name='blocktypeconfiguration',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block.blockconfigurationkeyword'),
        ),
        migrations.AlterField(
            model_name='blocktypeconfiguration',
            name='value',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='blocktypetranslation',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
