# Generated by Django 3.2.12 on 2022-03-07 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_alter_prerequisite_prerequisites'),
        ('block', '0003_block_coins_per_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockquestionpresentation',
            name='topic_grade',
        ),
        migrations.AddField(
            model_name='blockquestionpresentation',
            name='topic',
            field=models.ForeignKey(default=98, on_delete=django.db.models.deletion.PROTECT, to='kb.topic'),
            preserve_default=False,
        ),
    ]
