# Generated by Django 3.2.11 on 2022-01-07 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
        ('block', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='block.block')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
