# Generated by Django 3.2.11 on 2022-01-12 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0003_alter_questionttsasset_tts_file'),
        ('block', '0004_blockassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='questions',
            field=models.ManyToManyField(blank=True, to='kb.Question'),
        ),
        migrations.AlterField(
            model_name='block',
            name='type_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='block.blocktype'),
        ),
    ]
