# Generated by Django 3.2.12 on 2022-03-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_auto_20220307_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='coins_available',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='experience_points_available',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
