# Generated by Django 3.2.11 on 2022-01-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_auto_20220112_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockpresentation',
            name='deleted_timestamp',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp'),
        ),
        migrations.AddField(
            model_name='blockpresentation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
