# Generated by Django 3.2.11 on 2022-02-02 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0013_areaofknowledge_is_active'),
        ('block', '0007_auto_20220124_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='topic_grade',
            field=models.ForeignKey(help_text='This are the topics covered in this block', on_delete=django.db.models.deletion.PROTECT, to='kb.topicgrade'),
        ),
    ]
