# Generated by Django 3.2.13 on 2022-06-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0009_auto_20220525_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentblockquestionpresentationhistory',
            name='block_question_presentation',
        ),
        migrations.AddField(
            model_name='studentblockquestionpresentationhistory',
            name='block_question_presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='block.blockquestionpresentation'),
        ),
    ]
