# Generated by Django 3.2.13 on 2022-06-30 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0009_auto_20220525_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockquestionpresentation',
            name='block_presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='block.blockpresentation'),
        ),
    ]
