# Generated by Django 3.2.13 on 2022-06-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0010_auto_20220628_0514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentblockquestionpresentationhistory',
            name='block_question_presentation',
        ),
        migrations.AddField(
            model_name='studentblockquestionpresentationhistory',
            name='block_question_presentation',
            field=models.ManyToManyField(to='block.BlockQuestionPresentation'),
        ),
    ]
