# Generated by Django 3.2.13 on 2022-07-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_studenthomework_name'),
        ('block', '0010_alter_blockquestionpresentation_block_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='student_homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.studenthomework'),
        ),
    ]
