# Generated by Django 3.2.3 on 2021-06-16 18:19

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import parler.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('collectibles', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransactioncollectible',
            name='movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wallets.transaction'),
        ),
        migrations.AddField(
            model_name='studenttransactioncollectible',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
        migrations.AddField(
            model_name='collectibletranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='collectibles.collectible'),
        ),
        migrations.AddField(
            model_name='collectiblecategorytranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='collectibles.collectiblecategory'),
        ),
        migrations.AddField(
            model_name='collectiblecategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='collectibles.collectiblecategory'),
        ),
        migrations.AddField(
            model_name='collectible',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='collectibles.collectiblecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='collectibletranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='collectiblecategorytranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
