# Generated by Django 3.2.4 on 2021-07-01 05:20

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiblecategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='collectibles.collectiblecategory'),
        ),
    ]
