# Generated by Django 3.2.7 on 2021-11-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='collectiblecategory',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
