# Generated by Django 3.2.3 on 2021-06-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectible',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='collectiblecategory',
            name='slug',
        ),
        migrations.AlterField(
            model_name='collectible',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
