# Generated by Django 3.2.11 on 2022-02-02 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_initial'),
        ('collectibles', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='tier',
            field=models.CharField(choices=[('Common', 'Common'), ('Rare', 'Rare'), ('Legendary', 'Legendary'), ('Epic', 'Epic')], default='Common', max_length=32),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CollectiblePackPurchaseTransaction',
            fields=[
                ('withdraw_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallets.withdraw')),
                ('collectibles', models.ManyToManyField(blank=True, to='collectibles.Collectible')),
            ],
            options={
                'abstract': False,
            },
            bases=('wallets.withdraw',),
        ),
    ]
