# Generated by Django 3.2.4 on 2021-07-01 16:32

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0002_alter_collectiblecategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectiblecategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_categories', to='collectibles.collectiblecategory'),
        ),
    ]
