# Generated by Django 3.2.3 on 2021-06-16 18:15

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0002_auto_20210616_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectible',
            options={},
        ),
        migrations.AlterModelOptions(
            name='collectiblecategory',
            options={},
        ),
        migrations.RemoveField(
            model_name='collectible',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collectible',
            name='name',
        ),
        migrations.RemoveField(
            model_name='collectiblecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collectiblecategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='studenttransactioncollectible',
            name='name',
        ),
        migrations.CreateModel(
            name='CollectibleTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='collectibles.collectible')),
            ],
            options={
                'verbose_name': 'collectible Translation',
                'db_table': 'collectibles_collectible_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CollectibleCategoryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='collectibles.collectiblecategory')),
            ],
            options={
                'verbose_name': 'collectible category Translation',
                'db_table': 'collectibles_collectiblecategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
