# Generated by Django 3.2.11 on 2022-02-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0003_auto_20220202_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcollectible',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='collectiblecategory',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
