# Generated by Django 3.2.3 on 2021-06-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20210616_1253'),
        ('students', '0003_auto_20210616_1253'),
        ('collectibles', '0003_auto_20210616_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiblePurchaseTransaction',
            fields=[
                ('withdraw_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wallets.withdraw')),
                ('collectible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='collectibles.collectible')),
            ],
            options={
                'abstract': False,
            },
            bases=('wallets.withdraw',),
        ),
        migrations.CreateModel(
            name='StudentCollectible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('collectible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='collectibles.collectible')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='StudentTransactionCollectible',
        ),
    ]
