# Generated by Django 3.2.11 on 2022-02-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0004_auto_20220214_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectiblecategory',
            old_name='image',
            new_name='front_image',
        ),
        migrations.AddField(
            model_name='collectiblecategory',
            name='back_image',
            field=models.URLField(null=True),
        ),
    ]
