# Generated by Django 3.2.11 on 2022-02-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0004_auto_20220211_1410'),
        ('collectibles', '0004_auto_20220214_1309'),
    ]

    operations = [
    ]
