# Generated by Django 3.2.11 on 2022-02-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0005_auto_20220216_0822'),
        ('collectibles', '0005_merge_0004_auto_20220211_1410_0004_auto_20220214_1309'),
    ]

    operations = [
    ]
