# Generated by Django 3.2.11 on 2022-02-18 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0006_merge_20220216_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectible',
            name='price',
        ),
        migrations.AddField(
            model_name='collectiblecategory',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='collectiblepackpurchasetransaction',
            name='collectible_category',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='collectibles.collectiblecategory'),
            preserve_default=False,
        ),
    ]
