# Generated by Django 3.2.12 on 2022-04-24 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_is_new'),
        ('kb', '0013_typeinansweroption_case_sensitive'),
        ('audiences', '0001_initial'),
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativepersonnel',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='organization.Teacher'),
        ),
        migrations.AddField(
            model_name='schoolpersonnel',
            name='country',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='schoolpersonnel',
            name='zip',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('name', models.CharField(max_length=128, null=True)),
                ('language', models.CharField(max_length=128, null=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audiences.audience')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.grade')),
                ('students', models.ManyToManyField(blank=True, to='students.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='classrooms',
            field=models.ManyToManyField(blank=True, to='organization.Classroom'),
        ),
    ]
