# Generated by Django 3.2.12 on 2022-04-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220314_1014'),
        ('plans', '0005_alter_guardianstudentplan_student'),
        ('organization', '0003_auto_20220424_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrativepersonnel',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.RemoveField(
            model_name='school',
            name='group',
        ),
        migrations.RemoveField(
            model_name='school',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classrooms',
        ),
        migrations.AddField(
            model_name='classroom',
            name='enable_games',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='friday_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='friday_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='game_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='monday_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='monday_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='saturday_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='saturday_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organization.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='sunday_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='sunday_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='thursday_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='thursday_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='time_zone',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='tuesday_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='tuesday_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='wednesday_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='wednesday_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='schoolpersonnel',
            name='discountCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.discountcode'),
        ),
        migrations.AddField(
            model_name='schoolpersonnel',
            name='district',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organization.classroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='school',
            name='student_plan',
            field=models.ManyToManyField(blank=True, null=True, to='plans.StudentPlan'),
        ),
    ]
