# Generated by Django 3.2.3 on 2021-06-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20210616_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organizationpersonnel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.AlterModelOptions(
            name='schoolpersonnel',
            options={},
        ),
    ]
