# Generated by Django 3.2.12 on 2022-04-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_alter_guardianstudentplan_student'),
        ('organization', '0004_auto_20220425_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='school',
            name='student_plan',
            field=models.ManyToManyField(null=True, to='plans.StudentPlan'),
        ),
    ]
