# Generated by Django 3.2.3 on 2021-06-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_school_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolpersonnel',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=8, null=True),
        ),
    ]
