# Generated by Django 3.2.12 on 2022-06-15 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20220525_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpersonnel',
            name='school_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpersonnel',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.school'),
        ),
    ]
