# Generated by Django 3.2.13 on 2022-07-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20220616_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('schoolpersonnel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.schoolpersonnel')),
            ],
            options={
                'abstract': False,
            },
            bases=('organization.schoolpersonnel',),
        ),
        migrations.AddField(
            model_name='schoolpersonnel',
            name='has_order',
            field=models.BooleanField(default=False),
        ),
    ]
