# Generated by Django 3.2.12 on 2022-04-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20220425_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.classroom'),
        ),
    ]
