# Generated by Django 3.2.13 on 2022-07-11 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20220526_0028'),
        ('kb', '0016_auto_20220525_0236'),
        ('organization', '0006_auto_20220704_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdministrativePersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
                ('cancel_reason', models.TextField(blank=True)),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
                ('cancel_reason', models.TextField(blank=True)),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
                ('cancel_reason', models.TextField(blank=True)),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='schoolpersonnel',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='school',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='group',
            name='area_of_knowledges',
        ),
        migrations.RemoveField(
            model_name='group',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='group',
            name='internal_code',
        ),
        migrations.RemoveField(
            model_name='group',
            name='population',
        ),
        migrations.RemoveField(
            model_name='group',
            name='school_personnel',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='school',
            name='internal_code',
        ),
        migrations.RemoveField(
            model_name='school',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='school',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='school',
            name='student_plan',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='discountCode',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='position',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='school',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='school_name',
        ),
        migrations.AddField(
            model_name='group',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.classroom'),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='zip',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='schoolpersonnel',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.discountcode'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='friday_end',
            field=models.TimeField(default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='friday_start',
            field=models.TimeField(default=datetime.time(7, 0), null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kb.grade'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='monday_end',
            field=models.TimeField(default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='monday_start',
            field=models.TimeField(default=datetime.time(7, 0), null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='thursday_end',
            field=models.TimeField(default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='thursday_start',
            field=models.TimeField(default=datetime.time(7, 0), null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='tuesday_end',
            field=models.TimeField(default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='tuesday_start',
            field=models.TimeField(default=datetime.time(7, 0), null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='wednesday_end',
            field=models.TimeField(default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='wednesday_start',
            field=models.TimeField(default=datetime.time(7, 0), null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='type_of',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('CHARTER', 'Charter')], max_length=15, null=True),
        ),
    ]
