# Generated by Django 3.2.13 on 2022-07-05 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20220526_0028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0006_auto_20220704_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=8, null=True)),
                ('has_order', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriberSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='schoolpersonnel',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='school',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='group',
            name='area_of_knowledges',
        ),
        migrations.RemoveField(
            model_name='group',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='group',
            name='internal_code',
        ),
        migrations.RemoveField(
            model_name='group',
            name='population',
        ),
        migrations.RemoveField(
            model_name='group',
            name='school_personnel',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='school',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='school',
            name='student_plan',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='country',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='discountCode',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='district',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='identification_number',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='position',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='zip',
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.teacher'),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='coupon_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.discountcode'),
        ),
        migrations.AddField(
            model_name='school',
            name='zip',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='type_of',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('CHARTER', 'Charter')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
        migrations.AddField(
            model_name='teacherclassroom',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.classroom'),
        ),
        migrations.AddField(
            model_name='teacherclassroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.teacher'),
        ),
        migrations.AddField(
            model_name='subscriberschool',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
        migrations.AddField(
            model_name='subscriberschool',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.subscriber'),
        ),
        migrations.AddField(
            model_name='schoolclassroom',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.classroom'),
        ),
        migrations.AddField(
            model_name='schoolclassroom',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
    ]
