# Generated by Django 3.2.13 on 2022-07-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20220706_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='internal_code',
        ),
        migrations.RemoveField(
            model_name='school',
            name='slug',
        ),
    ]
