# Generated by Django 3.2.13 on 2022-07-09 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20220709_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='create_timestamp',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='deleted_timestamp',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='has_order',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='random_slug',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='update_timestamp',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='user',
        ),
        migrations.AddField(
            model_name='school',
            name='district',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='schoolpersonnel_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.schoolpersonnel'),
            preserve_default=False,
        ),
    ]
