# Generated by Django 3.2.12 on 2022-04-26 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20220425_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='school_personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.schoolpersonnel'),
        ),
    ]
