# Generated by Django 3.2.13 on 2022-07-11 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plans', '0009_alter_plan_area_of_knowledge'),
        ('organization', '0007_auto_20220711_2159'),
        ('payments', '0010_auto_20220711_2159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Principal',
            new_name='Subscriber',
        ),
        migrations.AddField(
            model_name='teacherclassroom',
            name='classroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.classroom'),
        ),
        migrations.AddField(
            model_name='teacherclassroom',
            name='order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.orderdetail'),
        ),
        migrations.AddField(
            model_name='teacherclassroom',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
        migrations.AddField(
            model_name='teacherclassroom',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.teacher'),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.orderdetail'),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.teacher'),
        ),
        migrations.AddField(
            model_name='schoolsubscriber',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
        migrations.AddField(
            model_name='schoolsubscriber',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.subscriber'),
        ),
        migrations.AddField(
            model_name='schooladministrativepersonnel',
            name='administrative_personnel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.administrativepersonnel'),
        ),
        migrations.AddField(
            model_name='schooladministrativepersonnel',
            name='order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.orderdetail'),
        ),
        migrations.AddField(
            model_name='schooladministrativepersonnel',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
        migrations.AddField(
            model_name='schooladministrativepersonnel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
    ]
