# Generated by Django 3.2.13 on 2022-07-05 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20220706_0142'),
        ('organization', '0008_auto_20220706_0147'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='school',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.discountcode'),
        ),
        migrations.DeleteModel(
            name='SchoolClassroom',
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.classroom'),
        ),
    ]
