# Generated by Django 3.2.13 on 2022-07-10 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20220709_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolteacher',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.teacher'),
        ),
    ]
