# Generated by Django 3.2.13 on 2022-07-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20220711_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='game_cost',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='time_zone',
        ),
        migrations.AddField(
            model_name='classroom',
            name='game_cost_percentage',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='classroom',
            name='goal_coins_per_day',
            field=models.IntegerField(default=6000),
        ),
        migrations.AddField(
            model_name='classroom',
            name='time_zone_offset',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classroom',
            name='time_zone_value',
            field=models.CharField(default='Etc/GMT', max_length=128),
        ),
    ]
