# Generated by Django 3.2.13 on 2022-07-06 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20220706_0142'),
        ('plans', '0010_teacherclassroomplan'),
        ('organization', '0010_auto_20220706_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriberschool',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='subscriberschool',
            name='expired_at',
        ),
        migrations.RemoveField(
            model_name='subscriberschool',
            name='is_cancel',
        ),
        migrations.RemoveField(
            model_name='subscriberschool',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='subscriberschool',
            name='order_detail',
        ),
        migrations.RemoveField(
            model_name='subscriberschool',
            name='period',
        ),
        migrations.RemoveField(
            model_name='subscriberschool',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscriberschool',
            name='price',
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='expired_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='is_cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.orderdetail'),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='period',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
