# Generated by Django 3.2.13 on 2022-07-06 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20220706_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.classroom'),
        ),
    ]
