# Generated by Django 3.2.13 on 2022-07-06 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_alter_schoolteacher_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriberschool',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
        migrations.AlterField(
            model_name='subscriberschool',
            name='subscriber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.subscriber'),
        ),
    ]
