# Generated by Django 3.2.13 on 2022-07-06 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_auto_20220706_0353'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscriberSchool',
            new_name='SchoolSubscriber',
        ),
    ]
