# Generated by Django 3.2.13 on 2022-07-06 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20220706_0142'),
        ('organization', '0016_rename_subscriberschool_schoolsubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='coupon_code',
        ),
        migrations.AddField(
            model_name='schoolpersonnel',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.discountcode'),
        ),
    ]
