# Generated by Django 3.2.13 on 2022-07-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_auto_20220706_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolpersonnel',
            name='school',
        ),
        migrations.AlterField(
            model_name='schoolteacher',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.teacher'),
        ),
        migrations.AlterField(
            model_name='teacherclassroom',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
