# Generated by Django 3.2.13 on 2022-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_auto_20220706_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolteacher',
            name='period',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherclassroom',
            name='period',
            field=models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=100, null=True),
        ),
    ]
