# Generated by Django 3.2.13 on 2022-07-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_teacherclassroomplan'),
        ('payments', '0010_auto_20220706_0142'),
        ('organization', '0019_auto_20220706_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolAdministrativePersonnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_timestamp', models.DateTimeField(editable=False, null=True, verbose_name='Deleted timestamp')),
                ('random_slug', models.SlugField(editable=False, unique=True)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
                ('cancel_reason', models.TextField(blank=True)),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('period', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('administrativePersonnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.administrativepersonnel')),
                ('order_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.orderdetail')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plan')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.school')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
