# Generated by Django 3.2.13 on 2022-07-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_schooladministrativepersonnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladministrativepersonnel',
            name='administrativePersonnel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.administrativepersonnel'),
        ),
        migrations.AlterField(
            model_name='schooladministrativepersonnel',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
        migrations.AlterField(
            model_name='schoolsubscriber',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
        migrations.AlterField(
            model_name='schoolsubscriber',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.subscriber'),
        ),
        migrations.AlterField(
            model_name='schoolteacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.school'),
        ),
        migrations.AlterField(
            model_name='schoolteacher',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.teacher'),
        ),
        migrations.AlterField(
            model_name='teacherclassroom',
            name='classroom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organization.classroom'),
        ),
    ]
