# Generated by Django 3.2.13 on 2022-07-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_auto_20220706_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolpersonnel',
            name='country',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='schoolpersonnel',
            name='zip',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
