# Generated by Django 3.2.13 on 2022-07-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_auto_20220708_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooladministrativepersonnel',
            old_name='administrativePersonnel',
            new_name='administrative_personnel',
        ),
        migrations.AlterField(
            model_name='teacherclassroom',
            name='classroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.classroom'),
        ),
    ]
