# Generated by Django 3.2.13 on 2022-07-08 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0016_auto_20220525_0236'),
        ('organization', '0024_auto_20220708_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kb.grade'),
        ),
    ]
