# Generated by Django 3.2.13 on 2022-07-08 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0026_auto_20220708_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherclassroom',
            name='classroom',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.classroom'),
        ),
    ]
