# Generated by Django 3.2.3 on 2021-06-08 21:46

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kb', '0004_auto_20210608_1446'),
        ('universals', '0002_auto_20210608_1446'),
        ('content', '0003_auto_20210608_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaOfKnowledge',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AddField(
            model_name='universaltopic',
            name='area_of_knowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='universals.universalareaofknowledge'),
        ),
        migrations.AddField(
            model_name='universaltopic',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_topics', to='universals.universaltopic'),
        ),
    ]
