# Generated by Django 3.2.3 on 2021-06-16 17:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('universals', '0003_auto_20210608_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universaltopic',
            options={},
        ),
        migrations.AlterModelManagers(
            name='universaltopic',
            managers=[
                ('_tree_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
