# Generated by Django 3.2.3 on 2021-06-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universals', '0004_auto_20210616_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universalareaofknowledge',
            name='hex_color',
        ),
    ]
