# Generated by Django 3.2.4 on 2021-07-01 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0003_alter_collectiblecategory_parent'),
        ('users', '0003_alter_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleCategoryHiddenProxyModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('collectibles.collectiblecategory',),
        ),
    ]
