# Generated by Django 3.2.12 on 2022-03-07 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kb', '0003_alter_prerequisite_prerequisites'),
        ('students', '0009_alter_studenttopicmastery_mastery_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicStudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('questions_answered', models.IntegerField(default=0)),
                ('correct_question', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicMasterySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_size', models.IntegerField(default=50)),
                ('mastery_percentage', models.IntegerField(default=90)),
                ('competence_percentage', models.IntegerField(default=60)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='kb.topic')),
            ],
        ),
        migrations.CreateModel(
            name='AreaOfKnowledgeStudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, verbose_name='Updated timestamp')),
                ('questions_answered', models.IntegerField(default=0)),
                ('correct_question', models.IntegerField(default=0)),
                ('accuracy', models.IntegerField(default=0)),
                ('area_of_knowledge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kb.areaofknowledge')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
