# Generated by Django 3.2.4 on 2021-06-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('manager', 'manager'), ('student', 'student')], default='user', max_length=120),
        ),
    ]
