# Generated by Django 3.2.13 on 2022-06-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('manager', 'manager'), ('guardian', 'guardian'), ('student', 'student'), ('principal', 'principal')], default='user', max_length=120),
        ),
    ]
