# Generated by Django 3.2.12 on 2022-02-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
