# Generated by Django 3.2.3 on 2021-06-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210617_2313'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinwallet',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
        migrations.AlterField(
            model_name='engagementwallet',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
    ]
