# Generated by Django 3.2.3 on 2021-06-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinWallet',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.account')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounting.account',),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('movement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.movement')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounting.positivemovement',),
        ),
        migrations.CreateModel(
            name='EngagementWallet',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.account')),
                ('current_level', models.PositiveSmallIntegerField(default=1, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('accounting.account',),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('movement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounting.movement')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounting.negativemovement',),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type_transaction',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='PaymentOption',
        ),
    ]
