# Generated by Django 3.2.11 on 2022-02-02 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20220120_2155'),
        ('wallets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinwallet',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coinWallet', to='students.student'),
        ),
    ]
