# Generated by Django 3.2.3 on 2021-06-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collectibles', '0004_auto_20210616_1253'),
        ('students', '0003_auto_20210616_1253'),
        ('wallets', '0002_auto_20210616_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.DeleteModel(
            name='TypeTransaction',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.AddField(
            model_name='engagementwallet',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
        migrations.AddField(
            model_name='coinwallet',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='students.student'),
        ),
    ]
