# Generated by Django 3.2.12 on 2022-06-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('backup_name', models.CharField(max_length=64)),
                ('backup_filename', models.CharField(max_length=255)),
                ('backup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
    