# Generated by Django 3.2.13 on 2022-07-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasebackup',
            name='backup_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='databasebackup',
            name='backup_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
