# Generated by Django 3.2.13 on 2022-07-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_auto_20220728_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasebackup',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='databasebackup',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready')], default='PROCESSING', max_length=128),
        ),
    ]
