# Generated by Django 3.2.13 on 2022-06-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasuretrack', '0017_auto_20220525_0236'),
        ('badges', '0003_auto_20220525_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbadge',
            name='weekley_treasure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='treasuretrack.weeklytreasure'),
        ),
    ]
