# Generated by Django 3.2.3 on 2021-06-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audiences', '0002_auto_20210616_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='hex_color',
        ),
    ]
