# Generated by Django 3.2.11 on 2022-01-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiences', '0002_audience_standard_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audience',
            name='standard_code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
