# Generated by Django 3.2.13 on 2022-08-26 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0002_subscription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='template name')),
                ('content', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created timestamp')),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
                ('success', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='reason note')),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emails.emailtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
