# Generated by Django 3.2.11 on 2022-01-05 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audiences', '0001_initial'),
        ('kb', '0004_auto_20220105_1403'),
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentplan',
            name='total_credits',
        ),
        migrations.RemoveField(
            model_name='studentplan',
            name='validity_date',
        ),
        migrations.AddField(
            model_name='studentplan',
            name='topic_grade',
            field=models.ManyToManyField(to='kb.TopicGrade'),
        ),
        migrations.AlterField(
            model_name='studentplan',
            name='audience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='audiences.audience'),
        ),
        migrations.DeleteModel(
            name='StudentPlanTopicGrade',
        ),
    ]
