# Generated by Django 3.2.3 on 2021-06-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20210616_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentplan',
            options={},
        ),
    ]
