# Generated by Django 3.2.13 on 2022-07-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0006_auto_20220525_0236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='stripe_monthly_plan_half_price_id',
            new_name='stripe_monthly_plan_preferential_price_id',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='stripe_yearly_plan_half_price_id',
            new_name='stripe_yearly_plan_preferential_price_id',
        ),
        migrations.AddField(
            model_name='plan',
            name='price_preferential_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_preferential_year',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
