# Generated by Django 3.2.13 on 2022-07-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_auto_20220704_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price_preferential_month',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_preferential_year',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
