# Generated by Django 3.2.13 on 2022-07-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_auto_20220704_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='area_of_knowledge',
            field=models.CharField(blank=True, choices=[('ALL', 'ALL'), ('ONE', 'ONE'), ('TWO', 'TWO')], default='ALL', max_length=255, null=True),
        ),
    ]
