# Generated by Django 3.2.13 on 2022-08-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_alter_plan_area_of_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='quantity_preferential_month',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='plan',
            name='quantity_preferential_year',
            field=models.IntegerField(default=2),
        ),
    ]
