# Generated by Django 3.2.13 on 2022-07-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_teacherclassroomplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherClassroomPlan',
        ),
    ]
