# Generated by Django 3.2.13 on 2022-08-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_auto_20220803_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price_month',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_year',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
