# Generated by Django 3.2.13 on 2022-08-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_plan_quantity_lower_limitr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='quantity_lower_limitr',
            new_name='quantity_lower_limit',
        ),
    ]
