# Generated by Django 3.2.13 on 2022-08-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_rename_quantity_lower_limitr_plan_quantity_lower_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='product_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
