# Generated by Django 3.2.13 on 2022-08-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_plan_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
