on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.PROD_SERVER_SSH_ADDRESS}} # IP address of the server you wish to ssh into
          username: ${{ secrets.PROD_SERVER_SSH_USERNAME }} # User of the server you want to ssh into
          password: ${{ secrets.PROD_SERVER_SSH_PASSWORD }} # User of the server you want to ssh into
          port: ${{ secrets.PROD_SERVER_SSH_PORT }} # User of the server you want to ssh into
          script: |
                    cd /home/albert/django-apps/learning_backend
                    git checkout .
                    git pull origin master
                    pipenv install
                    pipenv run python ./src/manage.py migrate
                    sudo systemctl restart gunicorn
                    sudo systemctl restart gunicorn


