name: Socrates Backend Build and Deploy

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          
      - name: Setup  Python 3.6 
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install Requirements 
        run: |
          pip3 install pipenv 
          pipenv install
          
      - name: Migrate Schema and Run Django server     
        run: |
          pipenv run
          python ./src/manage.py migrate
          python ./src/manage.py runserver
